### ISSUE TITLE
Change transfer functions to not use keepAlive

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/HydraDX-ui#1031]
Our transfer window uses transfer.keepAlive - it would be useful to add a checkbox for allowDeath so that users can sned everything

<img width="661" alt="image" src="https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/a9973f52-fd3b-4989-9eb8-500162613a09">

**Comment by jak-pan** [comment]
This should have been fixed some time ago. Default should be just transfer so no need for this cc @DuriSK

**Comment by jak-pan** [comment]
Fixed by #1208
