### ISSUE TITLE
Bug: routes displayed incorrectly for multi-hop trades

### ISSUE THREAD

**Issue by poliwop** [galacticcouncil/HydraDX-ui#1119]
It looks to me like all assets after the first asset are in the reverse order of what they should be? I am guessing this is just a display bug and that the transactions are created correctly, but I did not test this.
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/5674266/f799d5a6-4d3f-47a4-83e1-b3276ba0b8c9)
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/5674266/41163fd8-76ad-4cf3-adab-8dcbf3263a30)
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/5674266/4478d513-dafd-4332-84e0-3555d143f9f0)

**Comment by jak-pan** [comment]
Fixed
