### ISSUE TITLE
Wrong prices on Isolated pool detail tab

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/HydraDX-ui#1135]
e.g. current prices are around DOT = $10, NODL = $0.01
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/7eb67de9-4327-403b-a909-d629cbb8956b)

**Comment by green-jay** [comment]
design:
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/da047d3b-d164-4529-b14f-29fbc0e152e5)

**Comment by DuriSK** [comment]
Implemented as per design, in prod
