### ISSUE TITLE
External asset warning levels

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-ui#1218]
We should have multiple warning levels for external assets:

Red if user has admin rights. Display and explain with warning that admin can RUG or change anything any time. 
Yellow if user doesn't have admin rights. Display current warning about external asset.

For the red level we will need to check if admin is common account like treasury, relaychain, proxy with burnt keys or AH root account.

**Comment by jak-pan** [comment]
People already starting to abuse this. We need this ASAP. Also we should check if our parachain account on AH holds at least the amount of tokens that is minted on our chain. If not we should display RUG warning as admin of the token has burned tokens from our chain. We should probably suspend all actions with these tokens immediately.

**Comment by jak-pan** [comment]
This is related to #1219 as we will need to check the external asset status updates upon load

**Comment by DuriSK** [comment]
https://app.clickup.com/t/86byd6ch8

**Comment by jak-pan** [comment]
Partially fixed. Closing and opening new issue for admin key check.
