### ISSUE TITLE
Add logo for $STINK

### ISSUE THREAD

**Issue by imwebdevin** [galacticcouncil/HydraDX-ui#1221]
Was told to open an issue if I wanted to see the logo added to the UI. ~~I've attached the png below.~~ Learned that it needs to be an svg so I've replaced the png with an svg.

![Stanky_The_Hand ](https://github.com/galacticcouncil/HydraDX-ui/assets/126222174/7d7d742c-c419-4a82-8399-452a9b363afd)

**Comment by jak-pan** [comment]
Added
