### ISSUE TITLE
OTC show +9000 % market with external assets not added to local storage

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#1231]
when someone makes an otc order with an external asset, it appears this way if it hasn't been added to your local storage

should appear like n/a right?

appear this way after you added to local storage
![Screenshot_20240413_074727_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/7225c41b-fcc9-464b-ad69-8f29bfb1ca64)
![Screenshot_20240413_074521_Chrome](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/68adf9ca-8862-49c1-9f79-b54c7c8aa1a1)
![Screenshot_20240413_074518_Chrome](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/d5c8c4b9-f2eb-41f0-ab59-772eeb645165)

**Comment by jak-pan** [comment]
We should not show assets that are not added to the ui
