### ISSUE TITLE
Safari asset warning icon cut off

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-ui#1232]
<img width="310" alt="Screenshot 2024-04-15 at 18 56 48" src="https://github.com/galacticcouncil/HydraDX-ui/assets/3409250/b6b4e9fd-1ba3-456b-8931-f3bff9013bf6">
<img width="234" alt="Screenshot 2024-04-15 at 18 56 44" src="https://github.com/galacticcouncil/HydraDX-ui/assets/3409250/f73dd091-46e9-43e7-86a2-f86368e6a00a">

**Comment by nohaapav** [comment]
Fix in ui @galacticcouncil/ui@3.1.8
Pls upgrade deps
