### ISSUE TITLE
Metamask not working with app

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/HydraDX-ui#1234]
Env: PROD
Wallet: 0x7d5b401C887117a567F2F334976E34FddA73176e
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/0f8ca70d-1cf7-4b0f-8625-7a402a57d9a4)

Swap:
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/356db72b-20a3-4b33-89a5-006be3a3df03)

Conf. screen:
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/49586b17-b810-4bda-b142-d10c58134f07)
Calldata: 0x3b0514000000000000006062d558a2d90300000000000000000095d26133b9c200000000000000000000

Outcome:
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/cba61fbd-6363-4d41-a54b-a05c1273b640)
Address: 7KATdGb5Fs2qTdFJWpiCReZaTofs7WqQC5GfQkn9uBiE3emu
Provider: metamask
Message: {"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32603,"message":"evm error: Other(\"dispatch execution failed: BuyLimitNotReached\")","data":"0x","cause":null}}
Spec Version: 227

Transfer:
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/270c99bf-2ae2-4bbd-9908-73f1565b15f0)
0x4d0045544800c13fc088ad3bff128ef4cc15608180a47efef83c0000000000000000140000000f00406352bfc601
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/e412785c-c452-443e-b5f7-63e355594a7b)

Outcome:
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/5189d4dc-b661-4fec-b785-a611822e276c)
yet nothing in indexer, no amount is transferred

**Comment by DuriSK** [comment]
fixed
