### ISSUE TITLE
Displaying assets that are not added in default list

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-ui#1236]
We shouldn't show asset that were not added to the UI to users by default. We can add toggle to "show all assets with balance"

Also we could populate the name of this asset if it's known in the list and if we want to show it.

https://app.hydradx.io/wallet/assets?account=15FsX8EdUftorgXBjtgbdD1NesqVPwfJPL79V5JDvk2CCc9x

<img width="1287" alt="Screenshot 2024-04-16 at 19 50 20" src="https://github.com/galacticcouncil/HydraDX-ui/assets/3409250/ed827d1b-693f-4cee-9e6c-4f5c893b7127">

**Comment by jak-pan** [comment]
linked to #1231

**Comment by vkulinich-cl** [comment]
Done
