### ISSUE TITLE
Nodle RPC renamed

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/HydraDX-ui#1256]
Please change the Nodle RPC that's used in our CROSS-CHAIN UI - it's currently eden-rpc.dwellir.com and it has been renamed to nodle-rpc.dwellir.com

![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/9fe21623-5c4a-4222-84ba-d68e21e143ec)

**Comment by jvonasek** [comment]
fixed in #1261
