### ISSUE TITLE
Change wud warning to yellow and add logo

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#1263]
Removed their  admin keys using a proxy like pink

https://assethub-polkadot.subscan.io/extrinsic/6110778-2

![image-21](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/e7dfd86b-ffcb-435d-bcd1-d8f506516426)

![wud](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/0f725930-90bd-4498-8dde-721934af3edd)

**Comment by jvonasek** [comment]
added in #1268
