### ISSUE TITLE
 kilt logo is a little grey , and is missing the origin logo

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#1274]
![Screenshot_20240425_092808_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/96a021b4-042e-4a96-b48b-99e149973558)

**Comment by jak-pan** [comment]
This doesn't seem to be the case anymore. Can you retest?

**Comment by jak-pan** [comment]
If so please provide more information about environment

**Comment by joseJRJR** [comment]
Yep seems already fixed too
