### ISSUE TITLE
24h volume is missing

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#1275]
![Screenshot_20240425_094221_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/d5c94be1-6e1c-4f96-941e-2365bd958080)

**Comment by jak-pan** [comment]
Can you provide more info? I don't see this problem.

**Comment by joseJRJR** [comment]
> Can you provide more info? I don't see this problem.

already seems was fixed

after adding kilt to Omnipool, the volume from kilt does not appear, so i suppose that also affect the 24h volume, but now both appear

also seems like the other issue was fixed too

**Comment by jak-pan** [comment]
Okay we can test this - so it seems unless there is a volume for an asset the whole volume will fail to display.

**Comment by joseJRJR** [comment]
But there was some volume, cause i did one trade, even if is 1 usd ( that was my trade and other do also 1 usd) , should be counted

**Comment by jak-pan** [comment]
> But there was some volume, cause i did one trade, even if is 1 usd ( that was my trade and other person do also 1 usd) , should be counted

The volume is indexed and has delay in displaying in the LM / Stats page. There can be period of time until you see your trade counted.

**Comment by joseJRJR** [comment]
Mm ok makes sense, thanks 👍
