### ISSUE TITLE
Change WIFD to yellow by removing admin rights and add logo

### ISSUE THREAD

**Issue by dogwifdots** [galacticcouncil/HydraDX-ui#1285]
Dear team,
I looking for support to revoke admin rights and getting set to yellow on hydradx.

Asset details
{
  owner: 12ELtk1AQb3ftpN8RhUc7MHYT6jyq4MXFafkH3sKN46EJpiX
  issuer: 12ELtk1AQb3ftpN8RhUc7MHYT6jyq4MXFafkH3sKN46EJpiX
  admin: 12ELtk1AQb3ftpN8RhUc7MHYT6jyq4MXFafkH3sKN46EJpiX
  freezer: 12ELtk1AQb3ftpN8RhUc7MHYT6jyq4MXFafkH3sKN46EJpiX
  supply: 10,000,000,000,000,000,000
  deposit: 2,019,000,000
  minBalance: 1
  isSufficient: false
  accounts: 2
  sufficients: 0
  approvals: 0
  status: Live
}

![image](https://github.com/galacticcouncil/HydraDX-ui/assets/168309605/43a332d0-4f83-4302-adc1-74d1166047ac)

WIFD Logo - original (< 500 KB)
![WIFD](https://github.com/galacticcouncil/HydraDX-ui/assets/168309605/fd141d33-389e-4c22-aadc-1c01cfa82549)

WIFD Logo - small (< 30 KB)
![WIFD](https://github.com/galacticcouncil/HydraDX-ui/assets/168309605/01cc41a5-2908-4b12-99ca-39298cb4c977)

Further details to WIFD:
-> Token symbol: WIFD
-> Token ID (asset hub): 17
-> HydraDx token ID: 1000082

**Comment by jak-pan** [comment]
We will need .svg logo

**Comment by dogwifdots** [comment]
Hi, I converted our logo to svg, is 1 MB to big or okay on your end?

And thanks for the support, really dog frens around here! <3

![WIFD_logo](https://github.com/galacticcouncil/HydraDX-ui/assets/168309605/156a37f0-1bf1-48d5-b499-4103a4b74e10)

**Comment by jak-pan** [comment]
> Hi, I converted our logo to svg, is 1 MB to big or okay on your end?
> 
> And thanks for the support, really dog frens around here! <3
> 
> ![WIFD_logo](https://private-user-images.githubusercontent.com/168309605/326868962-156a37f0-1bf1-48d5-b499-4103a4b74e10.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTA3NDEsIm5iZiI6MTcxNDQ5MDQ0MSwicGF0aCI6Ii8xNjgzMDk2MDUvMzI2ODY4OTYyLTE1NmEzN2YwLTFiZjEtNDhkNS1iNDk5LTQxMDNhNGI3NGUxMC5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNTIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjJhYmY0Y2EzYjU2NzU3Zjk0NDdjZjFlY2VmNWQ3ZTZlZjlmOTdmN2Y2MDMwYWJhNDQ3YTkwNzdiODNjOWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.923lHAo4UA8mgyIATSbDfcDRUvUNE1U8Q55tFX_vCKA)

Hello, no it's not ok. SVG logo is vector file which you should get from the designer of the logo and it should be significantly smaller than the bitmap version

**Comment by dogwifdots** [comment]
Hello, got it. From mobile the only thing I could do is scaling down the bitmap version to the following smol version:
![WIFD_logo_smol](https://github.com/galacticcouncil/HydraDX-ui/assets/168309605/93c7ddfe-5687-4050-b25c-a14a9f9f5e6a)

Will power up my design tool as soon as I arrive at home.

**Comment by jak-pan** [comment]
> Hello, got it. From mobile the only thing I could do is scaling down the bitmap version to the following smol version: ![WIFD_logo_smol](https://private-user-images.githubusercontent.com/168309605/326881041-93c7ddfe-5687-4050-b25c-a14a9f9f5e6a.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTIwNTQsIm5iZiI6MTcxNDQ5MTc1NCwicGF0aCI6Ii8xNjgzMDk2MDUvMzI2ODgxMDQxLTkzYzdkZGZlLTU2ODctNDA1MC1iMjVjLWExNGE5ZjlmNWU2YS5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNTQyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2ZiZGQ0ZmY5NDk2NjE1YzRjMTAyYjkyMWNmMGM4ZGVkMmZlMWQ2YjFiM2MzYTYwYWM4M2RlOTI4NTU5OTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0jScxMV68olK1JuWzmTw6jGy-BJXiHgQIlOGoXUBpBk)
> 
> Will power up my design tool as soon as I arrive at home.

When you are at it please remove the white background if you don't want square logo.

**Comment by dogwifdots** [comment]
jak-pan, we did our best - maybe our best is not good enough... no background and it's SVG
![WIFDLOGO](https://github.com/galacticcouncil/HydraDX-ui/assets/168309605/0bcaf801-291b-4cd1-a699-80dd4d326037)

**Comment by dogwifdots** [comment]
Hello jak-pan,
Hello team,
Our design just sent the svg design.
![WIFD logo](https://github.com/galacticcouncil/HydraDX-ui/assets/168309605/217ec776-4cac-42bc-a75e-c70b2046063a)

**Comment by jak-pan** [comment]
> Hello jak-pan, Hello team, Our design just sent the svg design. 

Perfect

**Comment by dogwifdots** [comment]
Hey jak-pan, will the WIFD token image be updated today - want to give the community on TG some update. :)
Thanks for the support!

**Comment by dogwifdots** [comment]
Hey btw,
We burned admin rights
https://assethub-polkadot.subscan.io/extrinsic/6174134-2 
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/168309605/14e33922-e360-460b-b830-1a3156dea35e)

**Comment by lolmcshizz** [comment]
It seems you have not burned admin, but instead some pure proxy that is not admin. As you demonstrated on your first message in this issue, the admin for WIFD is account ending piX - you burned PP ending ADL.

Therefore you need to change admin of WIFD #17 to a PP before burning that pure proxy.

**Comment by dogwifdots** [comment]
> It seems you have not burned admin, but instead some pure proxy that is not admin. As you demonstrated on your first message in this issue, the admin for WIFD is account ending piX - you burned PP ending ADL.
> 
> Therefore you need to change admin of WIFD #17 to a PP before burning that pure proxy.

Thanks for replying!
Is there any documentation or further guidance? Will do so directly...

Can the logo please still already be updated? :D

**Comment by dogwifdots** [comment]
Created new PP:
https://assethub-polkadot.subscan.io/extrinsic/6178076-2

Transfered asset admin to PP:
https://assethub-polkadot.subscan.io/extrinsic/6178116-2

Result:
assets.asset: Option<PalletAssetsAssetDetails>
{
  owner: 12ELtk1AQb3ftpN8RhUc7MHYT6jyq4MXFafkH3sKN46EJpiX
  issuer: 12ELtk1AQb3ftpN8RhUc7MHYT6jyq4MXFafkH3sKN46EJpiX
  admin: 154pzAYT7yMQQosPwygwDe5bkUMXy4pCijFgRgdd9fgd7Q57
  freezer: 12ELtk1AQb3ftpN8RhUc7MHYT6jyq4MXFafkH3sKN46EJpiX
  supply: 10,000,000,000,000,000,000
  deposit: 2,019,000,000
  minBalance: 1
  isSufficient: false
  accounts: 2
  sufficients: 0
  approvals: 0
  status: Live
}

Killed PP wif admin right:
https://assethub-polkadot.subscan.io/extrinsic/6178136-2

Please help us dotted pups now to get a nice and shiny logo + no admin warning!

THANKS for all the support!

**Comment by lolmcshizz** [comment]
To be absolutely clear - **all 4 "admin" categories owner, issuer, admin & freezer must be "burned"**

![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/9bb214f4-e43c-4139-a078-15e9618821e0)

The warning is in place because as long as **any** of those are "live", the token supply is not "free".

**Comment by dogwifdots** [comment]
Hey lolmcshizz, Sorry first time...

Was the WIFD "admin" - owner, issuer, admin & freezer:
12ELtk1AQb3ftpN8RhUc7MHYT6jyq4MXFafkH3sKN46EJpiX

Created a new PP:
https://assethub-polkadot.subscan.io/extrinsic/6179575-2

Gave all rights to PP - result:
{
  owner: 15UYP3XxPk8oY89LvQJTbnSMeUj92d7sT8Sw8ejWYVr1xXX6
  issuer: 15UYP3XxPk8oY89LvQJTbnSMeUj92d7sT8Sw8ejWYVr1xXX6
  admin: 15UYP3XxPk8oY89LvQJTbnSMeUj92d7sT8Sw8ejWYVr1xXX6
  freezer: 15UYP3XxPk8oY89LvQJTbnSMeUj92d7sT8Sw8ejWYVr1xXX6
  supply: 10,000,000,000,000,000,000
  deposit: 2,019,000,000
  minBalance: 1
  isSufficient: false
  accounts: 2
  sufficients: 0
  approvals: 0
  status: Live
}

Killed PP:
https://assethub-polkadot.subscan.io/extrinsic/6179634-2

Now gud?

**Comment by dogwifdots** [comment]
Hey lovely @vkulinich-cl, @lolmcshizz,
Any Update? We have the highest volume in isolated pools at HydraDX by a mile wif > 20k USD 24h.

Please help us pups out...

**Comment by dogwifdots** [comment]
Hello well hydrated devs,
Thanks for letting us pups know but is their a timeline for this functionality that blocking our Dogwifdots getting the logo and confirmation it needs?
Please sir my dottedpup family 

Jokes aside you guys rock, and I will let you cook just can not handle the questionmark logo/ Admin warning anymore to a point it hurts growth

**Comment by jak-pan** [comment]
Sirs what is happening with this? @DuriSK 
We had everything even small logo.

**Comment by dogwifdots** [comment]
We are dehydrated already wif no sign of love for a dog wif dots by the HydraDX team :-(

How it feels like to wait getting hydrated...
![20240522_005100](https://github.com/galacticcouncil/HydraDX-ui/assets/168309605/32c555c3-2e0b-46bd-b2e3-b1610880dca7)

It's a meme by the WIFD community already...
![20240521_104246_0000](https://github.com/galacticcouncil/HydraDX-ui/assets/168309605/a9fcf425-e091-4fe3-b57d-9b41b6a71dee)

**Comment by vkulinich-cl** [comment]
Done
