### ISSUE TITLE
Add BNDT logo and Change Warning to Yellow

### ISSUE THREAD

**Issue by BANDITdotCAT** [galacticcouncil/HydraDX-ui#1287]
Please add $BNDT logo for BANDIT the CAT

![BNDT](https://github.com/galacticcouncil/HydraDX-ui/assets/168872308/3f402948-43bd-4d7d-acf8-7714a99bfdd0)

**Comment by BANDITdotCAT** [comment]
Hi Frens, looking to add the logo for BNDT 

Total Issuance: 69,420,000,000

-> Token symbol: BNDT
-> Token ID (asset hub): 8889
-> HydraDx token ID: 1000091

**Comment by BANDITdotCAT** [comment]
Thank you for working on this!

**Comment by jak-pan** [comment]
Sers we need .svg <50kb

**Comment by BANDITdotCAT** [comment]
Updated svg under 50kb

**Comment by BANDITdotCAT** [comment]
Also, Admin Rights have just been burned, please change warning to Yellow!

Proxy ID: 14L3Q6vsgnTg7fD3yHLV6Am34m4DsuFpwSvTDch3UdbfBQrR
Extrensic ID: [6243487-2](https://assethub-polkadot.subscan.io/extrinsic/6243487-2)

**Comment by BANDITdotCAT** [comment]
![Proxy burned](https://github.com/galacticcouncil/HydraDX-ui/assets/168872308/f6fc447f-e441-4163-917b-653cab3e55fc)

**Comment by vkulinich-cl** [comment]
Done
