### ISSUE TITLE
Some low liquidity fkery

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/HydraDX-ui#1288]
Users are still having issues with low liquidity pools when making small trades - for example the below tx:

https://hydradx.subscan.io/extrinsic/0x3986312bedba5a1f29b337715445559ab23ff7d6e38b6b95507559ac40e8cf42

Failed due to it hitting their slippage amount - user tried many times as they didn't understand (I'll reiterate here about needing those error messages in the notification panel) what was the issue.

If you try and make the trade now, you can see that it tries to route through INTR<>HDX pool as that provides the best price, but slippage setting causes it to fail. Perhaps we need some additional logic that will choose an alternative route if the trade would fail based on user slippage settings?
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/49d6c2a2-8d16-4d2c-9dfb-1f10d7fcc94a)

**Comment by jak-pan** [comment]
This is not the same swap as in screenshot and also the swap is direct omnipool swap I guess we use router always ? cc @nohaapav

**Comment by jak-pan** [comment]
This seems as stale... @lolmcshizz do we have still reports of this?
