### ISSUE TITLE
BEEFY broke the UI

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/HydraDX-ui#1304]
new memecoin BEEFY just dropped on Hydration - I managed to ape some (and trading is possible) but UI is not able to get a price and spins endlessly with the following error:

![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/b246a42a-663d-4471-8bd2-aca2480d1fd2)

As you can see, it allows trading but spot price rekt:

![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/7afc5638-9648-48f6-ae83-30b09c2da8fd)

**Comment by mrq1911** [comment]
looks like apps issue @nohaapav

**Comment by mrq1911** [comment]
BEEFY being 2 decimals possibly causing this

**Comment by mrq1911** [comment]
will be fixed by https://github.com/galacticcouncil/sdk/issues/52

**Comment by nohaapav** [comment]
SDK part done (XYK) .. 

PR: https://github.com/galacticcouncil/HydraDX-ui/pull/1312

**Comment by polkadotbeefy** [comment]
@lolmcshizz thanks for reporting and thx to the devs for fixing this. 🙌

Looks like it works:

<img width="572" alt="image" src="https://github.com/galacticcouncil/HydraDX-ui/assets/169208724/dd01bd84-c9f6-4d41-95bd-b21b944486b2">

<img width="722" alt="image" src="https://github.com/galacticcouncil/HydraDX-ui/assets/169208724/3bfd4bd8-832d-44f3-9f66-845604b585e0">

**Comment by DuriSK** [comment]
fixed
