### ISSUE TITLE
$ values for external assets rugged from wallet page

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/HydraDX-ui#1320]
$ values no longer showing for external assets
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/cd9e9a91-0d29-4efb-931b-17484b21bb71)

Values still showing on trade page asset selector
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/182995ae-66c9-425c-a4c7-3fb6c14e900b)

**Comment by DuriSK** [comment]
fixed
