### ISSUE TITLE
Bnd and catwift, were deleted from UI, at least for me on NovaWalletApp 

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#1325]
I cant even add again, not appear the pools, were deleted

![Screenshot_20240522_110552_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/a10fb38b-ee7a-4960-b748-aea15f4494ae)

**Comment by joseJRJR** [comment]
Ok i know the problem,  the only way to add is from wallet tab, clicking if you already have the token

was trying to add the cat token, not appear when trying to add from swap page


https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/1f05cec1-03ed-4977-bcd5-5c04abffc29d

**Comment by DuriSK** [comment]
fixed
