### ISSUE TITLE
Change BORK logo and update admin rights warning (yellow)

### ISSUE THREAD

**Issue by dogwifdots** [galacticcouncil/HydraDX-ui#1346]
WOOF team,
I BORKed it again... new token for the pups...

Ticker: $BORK
Name: BORK
Asset Hub ID: 690
HydraDX ID: 1000148 
Total Supply: 690

Admin rights -> PP killed:
https://assethub-polkadot.subscan.io/extrinsic/6353468-2

{
  owner: 15K8mw5yYmaciAo7vx7CQZHfiXEh689WboyNKXPtm5gqfjG3
  issuer: 15K8mw5yYmaciAo7vx7CQZHfiXEh689WboyNKXPtm5gqfjG3
  admin: 15K8mw5yYmaciAo7vx7CQZHfiXEh689WboyNKXPtm5gqfjG3
  freezer: 15K8mw5yYmaciAo7vx7CQZHfiXEh689WboyNKXPtm5gqfjG3
  supply: 6,900,000,000,000
  deposit: 2,019,000,000
  minBalance: 1
  isSufficient: false
  accounts: 2
  sufficients: 0
  approvals: 0
  status: Live
}

BORK logo in black-white (round):
![BORK_4](https://github.com/galacticcouncil/HydraDX-ui/assets/168309605/ae599bf8-dd9f-4436-8fff-c1d9040a6088)

BORK logo in black-white (square):
![BORK](https://github.com/galacticcouncil/HydraDX-ui/assets/168309605/c60ebcce-7735-4570-9282-ed8d6c1eaa5a)

**Comment by dogwifdots** [comment]
Wen BORK?

**Comment by DuriSK** [comment]
Added
