### ISSUE TITLE
Add Logos to Pendulum assets

### ISSUE THREAD

**Issue by annatekl** [galacticcouncil/HydraDX-ui#1429]
We would like to add logos to the Pendulum assets:

Stellar BRL
![BRL (2)](https://github.com/galacticcouncil/HydraDX-ui/assets/138758794/48ba63fa-2e5d-42cd-ba5d-6d49588fad2f)

Stellar AUDD
![AUDD (3)](https://github.com/galacticcouncil/HydraDX-ui/assets/138758794/9268d592-c95f-4231-be39-208b1f77f8dc)

Stellar Lumen
![XLM (7)](https://github.com/galacticcouncil/HydraDX-ui/assets/138758794/037d2fca-8290-42c0-9383-1c649b5fbaf8)

Stellar NGNC
![NGN (3)](https://github.com/galacticcouncil/HydraDX-ui/assets/138758794/2500f5d4-f131-46e3-bfee-2488a80b14e6)

Stellar USDC
![USDC (2)](https://github.com/galacticcouncil/HydraDX-ui/assets/138758794/efa5f5f5-b4f0-43a2-92dc-cbd4b2077a2b)

**Comment by jak-pan** [comment]
Added

**Comment by annatekl** [comment]
Hi @jak-pan open the app and i am trying to add new asset, I don't see the icons for Pendulum
<img width="640" alt="Screenshot 2024-07-03 at 09 36 54" src="https://github.com/galacticcouncil/HydraDX-ui/assets/138758794/31261e64-c476-4cd8-bb26-a79a90243efe">

**Comment by jak-pan** [comment]
You will see them only after adding to the UI i.e. 
<img width="160" alt="Screenshot 2024-07-03 at 18 38 56" src="https://github.com/galacticcouncil/HydraDX-ui/assets/3409250/2cfce97d-9092-4e96-8017-8476f728ee6a">

**Comment by jak-pan** [comment]
This is now being fixed by the PR should be in soon ^
