### ISSUE TITLE
Add an indicator / sign for tokens that not just burned admin rights but also burned LP

### ISSUE THREAD

**Issue by dogwifdots** [galacticcouncil/HydraDX-ui#1439]
Woof, hey you lovely hydrated people,

Currently you guys are just tracking the admin rights status, which is like the bare minimum.
But for the upcoming degen memecoin season on Polkadot (Hydration), we need a rug proof sign to track if the LP was burned.

The procedure is identical to the admin rights burn on AH but this time the Pure Proxy (PP) is being created on Hydration. The PP is providing the liquidity (LP) and is killed after.

Projects that performed that procedure WUD, BUNS, WIFD and BORK. I am not in contact with the WUD dev, so I will just speak in the issue for BUNS, WIFD and BORK.

BUNS LP BURN
https://hydration.subscan.io/extrinsic/5385652-2

WIFD LP BURN
https://hydration.subscan.io/extrinsic/5411129-2

BORK LP BURN
https://hydration.subscan.io/extrinsic/5404502-2

I would love to see something like a green sign for those tokens.

Your 
dog wif dots dev

**Comment by jak-pan** [comment]
This does not seem like something we would do.
