### ISSUE TITLE
Empty page "cross-chain" when connecting a wallet Сhrome/Firefox

### ISSUE THREAD

**Issue by babikov** [galacticcouncil/HydraDX-ui#1459]
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/7600313/c22d1621-c79f-4cc1-90ae-e1738be6d4e0)
Browser console:
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/7600313/a778a57b-bb07-47f3-afa4-a38b153176ed)

**Comment by jak-pan** [comment]
This has been fixed now
