### ISSUE TITLE
enable sending DOT from asset hub to hydration

### ISSUE THREAD

**Issue by hitchhooker** [galacticcouncil/HydraDX-ui#1473]
enable sending DOT from asset hub to hydration
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/15621959/8b170a10-bad8-40c1-9ee7-e6d2a7b8eabb)
UI requires to send DOT from asset hub to relay to hydration atm

**Comment by jak-pan** [comment]
This is a technical limitation currently. We need to wait for runtime support hopefully in coming weeks.
