### ISSUE TITLE
Cross-chain UI, take into account locked tokens in governance

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#191]
having tokens locked in governance of Polkadot, these still appear available in the Cross-chain section, so the user will find it strange that him cannot transfer part of that balance

It is a UI error, because the calculation is correct
You can see that i have 1 DOT locked in governance, so in the Cross-chain section, should appear only 1.4 available, but still appear 2.4 ( take in account the locked in governance)

![Screenshot_2023-01-28-00-02-07-012_io novafoundation nova market](https://user-images.githubusercontent.com/123791232/215241228-ac473580-8c8e-4c9b-ac2d-858ea9ae94ed.jpg)
![Screenshot_2023-01-28-00-02-33-820_io novafoundation nova market](https://user-images.githubusercontent.com/123791232/215241229-09335885-5666-492f-8cc9-c3d1be54289b.jpg)

**Comment by nohaapav** [comment]
Fixed in apps v1.1.11
