### ISSUE TITLE
New Transaction type for stucked transactions

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/HydraDX-ui#192]
Issue:
Some pending transactions might be stucked, and then they are "forever"displayed in ongoing transactions.

Solution:
If transaction is ongoing longer than 1 minute, please change type of transaction to "unknown" and move it to "completed transactions section"

<img width="357" alt="newTransactionType" src="https://user-images.githubusercontent.com/97346452/215484478-b7c622f2-5662-4905-b90f-985d3602d7ef.png">

Design:
https://www.figma.com/file/eqzR2azTracqA8Vv0y4GUv/%F0%9F%96%A5--Hydra-%7C-Desktop-Library?node-id=10533%3A202410&t=vSgwi1mT60Nh9igk-4

**Comment by vkulinich-cl** [comment]
It has been implemented
