### ISSUE TITLE
Add Total 24H Volume to Top of LIQUIDITY page [Basilisk & Hydra]

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/HydraDX-ui#195]
Next to the TVL at the top of the LIQUIDITY page, we should also see the total 24h volume for all pools. 
24h volume for platform, should represent sum of 24h volumes of all pools.(We already have correct 24h volume calculation for single pool(Basilisk) and asset(Hydra)

Added on design:
https://www.figma.com/file/eqzR2azTracqA8Vv0y4GUv/🖥--Hydra-%7C-Desktop-Library?node-id=6948%3A112914&t=B4yAQ7EfeBumFpFj-0

<img width="722" alt="image" src="https://user-images.githubusercontent.com/97540577/216018638-d4752dff-a0da-4c5e-bd45-69fafed5c83a.png">

**Comment by vkulinich-cl** [comment]
It has been implemented
