### ISSUE TITLE
Displaying APR through the pool&farms flow [Basilisk First&then Hydra]

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/HydraDX-ui#214]
Inform user about available APR through the pools&farms page.

### APR calculation:
For basilisk, we need/are currently dividing computed apr /2. Thats because we are showing rewards just for one token. This needs to be still used.

For Hydra we dont need to do /2.

### Rounding:
Ranges and current APR should be displayed as integer, without decimal places.
Rounding should be based on first decimal number.
IF APR <1, than show two decimal places for it.

### Formats of APR
We would like to display APR in more formats to give user better decision ability:
- In form of range, where we would display min and max APR for given single incentive=>
minAPR=APR*loyaltyCurve.initialRewardPercentage
maxAPR= calculated APR
- In form of single number, which would represent current APR(just in farming incentives which user is in, otherwise we dont have loyaltyFactor)
current_APR=APR*currentLoyaltyFactor

Starting Loyalty Factor(initialRewarsPercentage):
LoyaltyCurve can be found for every yield farm, using yieldFarm(poolId,globalfarmId,yieldFarmId)
This attribute represents percentage, at which rewards are calculated.
This attribute is in percentages (between 0 and 0.999999) and its 18dp.
So 500,000,000,000,000,000 would mean farm starts at 50% rewards.
<img width="402" alt="Screenshot 2023-02-15 at 19 49 34" src="https://user-images.githubusercontent.com/97346452/219124773-cd2ff141-4e81-42e4-8a31-9f5b0cb4e418.png">

### General Info about available farming incentives:
<img width="930" alt="Screenshot 2023-02-15 at 19 43 34" src="https://user-images.githubusercontent.com/97346452/219123792-cd6b45ef-4fd3-426f-9016-c772e5b232be.png">

minAPR=APR*loyaltyCurve.initialRewardPercentage
maxAPR=calculated APR

### Join farm screen & join extra farm screen (farms which are user not in)
<img width="266" alt="Screenshot 2023-02-16 at 11 32 19" src="https://user-images.githubusercontent.com/97346452/219340783-b4aa927f-dc3e-4942-b754-b311ee717fac.png">

<img width="299" alt="Screenshot 2023-02-16 at 21 47 54" src="https://user-images.githubusercontent.com/97346452/219483376-be6d2a3f-468a-43c9-a108-6052de557007.png">

minAPR=APR*loyaltyCurve.initialRewardPercentage
maxAPR=calculated APR

In this case we are not displaying Actual APR.

### APR displayed on specific LM position
<img width="741" alt="Screenshot 2023-02-16 at 11 19 02" src="https://user-images.githubusercontent.com/97346452/219339154-fedd07e0-71e3-4a6e-82c1-21b9b0be290b.png">

For every farming incentive, in which user has entered, we would like to display here actual APR.
actual APR=calculated APR * current loyalty factor (loyalty factor needs to be checked for every specific incentive separately)

### Farms details screen (where user is already in)
<img width="428" alt="Screenshot 2023-02-16 at 21 41 47" src="https://user-images.githubusercontent.com/97346452/219482352-803204a1-7b3b-488a-86d8-bcdd15fa1481.png">

minAPR=APR*loyaltyCurve.initialRewardPercentage
maxAPR=calculated APR

actual APR=APR*currentLoyaltyFactor

For available farms(at the bottom) display:
minAPR=APR*loyaltyCurve.initialRewardPercentage
maxAPR=calculated APR

### Farm detail screen with loyalty chart(where user is already in)
<img width="340" alt="Screenshot 2023-02-16 at 15 11 50" src="https://user-images.githubusercontent.com/97346452/219391030-af4a28b6-649c-402e-849f-0625c31f9b89.png">

minAPR=APR*loyaltyCurve.initialRewardPercentage
maxAPR=calculated APR

actual APR=APR*currentLoyaltyFactor

User should be also informed by "marker" where currently he is on loyalty curve.

**Comment by vkulinich-cl** [comment]
Implemented, so it can be closed
