### ISSUE TITLE
Stepper for multiple transactions

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/HydraDX-ui#297]
Given user is going to sign multiple transactions (for example entering multiple farms)
Than at the beginning of signing flow, he should be informed that this process would require more steps (at the top of the screen)
And if first transaction goes through, stepper should move to second state

For transactions with just one step, dont display this flow

Design:
https://www.figma.com/file/eqzR2azTracqA8Vv0y4GUv/%F0%9F%96%A5--Hydra-%7C-Desktop-Library?node-id=21415-193220&t=DtDWZuvzcACc9fgl-4

**Comment by vkulinich-cl** [comment]
Done
