### ISSUE TITLE
As user, i want to be able to claim my tokens from vesting, while im in "shadow wallet"mode

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/HydraDX-ui#301]
General change of "shadow wallet" feature:
If user is connecting with account, which we can identify as proxied account
Than user should be able to choose proxy account with which he wants to sign transactions
And this account should be connected to platform in the background
And if user wants to perform action with proxied account
Proxy account should be used for signing

Specific case for vesting claim:
If user is connected with proxied account, and he has some tokens to claim from vesting, he should be able to do so by signing transaction with proxy (delegated) account

Flow:
![InvestorClaim](https://user-images.githubusercontent.com/97346452/230184752-01023009-5e3c-4a0b-95ec-82c69471057d.jpg)

**Comment by vkulinich-cl** [comment]
Implemented
