### ISSUE TITLE
Claim all button rework

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/HydraDX-ui#303]
As is:
User will hover over Claim all button
Claimable amounts are displayed
And when user click on this button
Claiming process starts

To be:
User will hover over "Farming rewards" button
Claimable amounts are being displayed
And if user has any rewards to claim
He should be able to click on "Claim all" button
And claiming process should start

Design HydraDx:
https://www.figma.com/file/eqzR2azTracqA8Vv0y4GUv/%F0%9F%96%A5--Hydra-%7C-Desktop-Library?node-id=22655-242697&t=tnvjymxrNeFu5sBJ-4

Design Basilisk:
https://www.figma.com/file/HZt2Xm6sfGWsI3vnnnaMC9/%F0%9F%96%A5--Basilisk-v0.5-%7C-Desktop?node-id=16706-179368&t=5RFkmrCz4YOfcrPD-4

**Comment by vkulinich-cl** [comment]
Implemented
