### ISSUE TITLE
Kill global loading on init

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/HydraDX-ui#34]
<img width="246" alt="Screenshot 2022-12-06 at 21 46 37" src="https://user-images.githubusercontent.com/2580779/206019461-a8529ee2-6882-4e3b-9612-639ac7d63546.png">
this is not a flash game💩

**Comment by obsivac-cleevio** [comment]
the loading is present when creating a polkadot `ApiPromise` - without the promise the app can't do anything, so we're displaying a short loading screen

**Comment by lumir-mrkva** [comment]
establishing ws connection can take long time, i will rather see empty app than this screen

**Comment by vkulinich-cl** [comment]
done
