### ISSUE TITLE
Trade app sells you 0 tokens

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/HydraDX-ui#405]
UI should validate that you are not getting 0 tokens from your trade. Especially in the case of DCA where it could drain your whole budget this way if you specified trade size to be too small.

<img width="585" alt="Screenshot 2023-05-30 at 11 29 49" src="https://github.com/galacticcouncil/HydraDX-ui/assets/2580779/fd23407f-006d-4e63-b45e-bca67fc693ca">

Min. limit should be always at least 1 not 0.

**Comment by jak-pan** [comment]
Looks fixed
