### ISSUE TITLE
External account sign transaction

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/HydraDX-ui#556]
Instead of sign transaction on external account/ view as account we should provide a link to open the transaction in polkadot.js for user to be able to sign the tx like so

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.hydradx.cloud#/extrinsics/decode/0x01020431

where: `https://polkadot.js.org/apps/?rpc=`**${current_rpc}**`#/extrinsics/decode/`**${encoded_call_data}**

**Comment by jvonasek** [comment]
merged in #1180
