### ISSUE TITLE
MM Split trade bug

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/HydraDX-ui#766]
How to reproduce:

- Connect Metamask
- Do a Split trade
- Place trade -> Sign transaction

![Image](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/10a7a455-da2d-401e-824f-c36a31d30d4b)

**Comment by mrq1911** [comment]
which asset combination you trade?

**Comment by nohaapav** [comment]
have to disable XYK on ui side ..

**Comment by green-jay** [comment]
problem also for non xyk trades, let's see if that fixes it

**Comment by green-jay** [comment]
still a problem @nohaapav

**Comment by DuriSK** [comment]
Cannot reproduce, seems like it has been fixed by number of EVM fixes
