### ISSUE TITLE
UI frozen after changing fee payment asset

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/HydraDX-ui#768]
- requested WETH from faucet
- connected using normal substrate wallet
- WETH wasn't market as fee payment asset so I couldn't do any transactions (option wasn't highlighted in wallet to change it to WETH)
- UI prompted me to change fee payment asset when trying to do a trade
- WETH wasn't on the list (it was blank)
- Used TC account to add WETH as fee payment asset in multiTransactionPayment.acceptedCurrencies
- WETH appeared on the list
- Selected it and signed tx to change it
- Review transaction details modal still open and no way of closing it or clicking out of it (completely unresponsive)
- Refreshing the page allowed me to continue on as normal
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/180c4130-d8c0-4c6d-ae10-f8ca23d9456c)

**Comment by jvonasek** [comment]
Can you provide reproduction video and type/version of your browser?

I can't seem to reproduce the frozen UI issue. After I change payment asset, I am able to close the trabsaction detail modal without any issue

**Comment by DuriSK** [comment]
fixed
