### ISSUE TITLE
Subsocial origin chain blank circle on OTC page

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/HydraDX-ui#769]
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/e20bb006-f6a4-4ba8-882b-6c44c23d483e)

**Comment by lolmcshizz** [comment]
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/bc7fb9c0-3adb-4b97-87a9-aa8fbd956532)
Also on liquidity page

**Comment by jvonasek** [comment]
Blank circle will not show now, but the problem behind this issue is this:

SUB has defined `parachainId=2100` but there is no exported parachain with this ID in the config from `@galacticcouncil/xcm` package

**Comment by nohaapav** [comment]
comin soon

**Comment by jak-pan** [comment]
Fixed
