### ISSUE TITLE
Discrepancy on swap Ui about tx fees

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#775]
On the UI to do the swaps appear HDX on tx fees, even if WETH is like asset fee, and when go to the next pop up, appear weth like tx fees. So is a little discrepancy 

![IMG_20231128_125401_897](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/48637dbf-618d-4b5a-90ef-8b8e3b7361c2)
![IMG_20231128_125401_520](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/cc5bf633-03d5-4915-a199-13add36d3a7d)

**Comment by jak-pan** [comment]
You always pay the fee with WETH while using Metamask. This will be fixed so that the fee payment option is disabled for now.

**Comment by DuriSK** [comment]
Fee payment always WETH for EVM
Will change soon, but for now correct behaviour
