### ISSUE TITLE
HDXb not available on OTC order creation

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/HydraDX-ui#783]
HDXb is not available to select in the `OFFER` or `YOU GET` fields of the OTC UI.

![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/30c8dc26-ccd5-42e5-8463-561c1b8ea478)

Orders created outside of the UI also do not show the HDXb logo

![image](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/27f62403-be79-42c5-a492-0cc8bf91155b)

**Comment by DuriSK** [comment]
Solved, bonds available on OTC creation
