### ISSUE TITLE
Liquidity total locked is not counting value of the LRNA

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/HydraDX-ui#798]
On individual positions, you can see the value of the position underlaying asset + LRNA, but the sum in total locked is just of underlaying assets.

The value of the LRNA should be summed up as well.

<img width="683" alt="Screenshot 2023-12-07 at 0 48 55" src="https://github.com/galacticcouncil/HydraDX-ui/assets/2580779/f577ef57-d34a-4852-81b9-5f3b851e6a5d">

I would expect total locked to be $50.23 there.

**Comment by jvonasek** [comment]
fixed in #940
