### ISSUE TITLE
Feedback about OTC tab

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#805]
Feedback from an user :

to upgrade interface of OTC tab, I suggest :
- add possibility to filter the token, to more easy search on the list, with the token A & B
- add column Pool Price, to have comparaison between Pool price and OTC Price
- same in %
- possibility to hide all OTC deal more than 10% gap with the pool (or others number it's the idea)

I also want to add dynamic pricing e.g. 10% discount to spot price of a tkn

also, an option who make automatic trade inside omnipool if it's give more or equal of the OTC order.
to close OTC order inside omnipool if the omnipool respect condition of the otc order

![image-20](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/d1c5d589-6337-4263-827c-d0e8cca31c79)

**Comment by DuriSK** [comment]
Lot of feedback added in https://github.com/galacticcouncil/HydraDX-ui/issues/933
