### ISSUE TITLE
Fail dca/split trade with slippage lower than 1%

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#807]
Seems like in  the dca orders recommend on the swap site (spli trade) If the slippage settings are lower than 1% will fail,

So my feedback is:   should separate the slippage settings then

Cause for swaps trades i prefer had an tiny slippage ( something like 0.1 or 0.5 %) and for the dca/split trades is mandatory use at least 1%

I dont want change each time

Save one for dca orders
Save one for  single swaps
Or do it on the backend

Also i recommend remove the option of 0.5 from dca slippage setting, cause we know that is lower than 1% will fail with " trade limit reached"

<img width="498" alt="Screenshot_2023-12-08_at_17 08 24" src="https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/03f540f0-4b1f-4d57-be40-4f79f089a5c2">

![Screenshot_20231208_123000_Chrome](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/df54749d-6179-4668-af39-cfee2caca99b)

**Comment by DuriSK** [comment]
Solved by adding slippage options for DCA and for SWAP
