### ISSUE TITLE
Not appear the HDXb when  withdrawn shares from xyk poll

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#826]
Only appear the HDX and not the HDXb, also not logo on liquidity tab, when i click my positions or on wallet tab either

![Screenshot_20231218_054820_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/9e8cc707-14dc-45db-8ef0-198a089f905b)

![Screenshot_20231218_055021_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/083ac918-b4f7-4d59-880d-95946356ed9e)
![Screenshot_20231218_055011_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/f27fb8ff-217e-4ac2-8e97-4c2c254f8aa8)

**Comment by vkulinich-cl** [comment]
Fixed
