### ISSUE TITLE
Wallet tab - missing the hdx/hdxb liquidity on the balance

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#831]
I had 2.7k on the pool, but on the liquidity balance only appear the 3$ from the DOT
![Screenshot_20231219_134821_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/f644f010-e9a6-46e1-ac6c-f220bd192187)

**Comment by DuriSK** [comment]
Fixed
