### ISSUE TITLE
Titles on Treasury stats page

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/HydraDX-ui#833]
This should say "Treasury composition" instead of "Omnipool Composition"
![image](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/5fa9d717-6f86-4757-b40e-a698e07d8e3e)

Also link is https://app.hydradx.io/stats/POL instead of https://app.hydradx.io/stats/treasury

**Comment by vkulinich-cl** [comment]
Fixed
