### ISSUE TITLE
Warning ledger dont supported

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#834]
Put an warning on the xcm tab that ledger dont support HydraDX 

There are users that dont check that and is annoying, so at least put the warning like with cexs?

**Comment by joseJRJR** [comment]
With bull coming this seems will become very frequently,  so at least put the warning so dont blame us
![Screenshot_20231222_084039_Telegram](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/e2527eea-6708-4e16-949f-9b1f55041236)
![Screenshot_20231222_084110_Telegram](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/1b288558-f8f0-4ac4-82ab-435fda1b6a95)

**Comment by joseJRJR** [comment]
![Screenshot_20231225_232756_Telegram](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/c51f7949-cb4d-410f-81d4-09ea2d6aa9cd)

**Comment by nohaapav** [comment]
in master

**Comment by joseJRJR** [comment]
> in master

Can you showme how should appear? Since i connect but not appear any warning?
