### ISSUE TITLE
Otc site refresh when try to fill the NO partially fillable 

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#836]
There are 2 examples, the thing that i see on common is that are complete fill, not partial allowed so something to check

https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/8f68872d-d54a-4dc6-ab8f-a9b03ef33a8c

https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/01040b95-72ba-40fd-89f5-c47e0d1699cc

**Comment by joseJRJR** [comment]
Ok i confirmed that only refresh when is an ltc order that have disabled the partially fillable option 
On the follow videos can see that even i can partial fill a hdx<> hdx otc order ( not appear the noti of successful but it was) , and with the not partially , refreshed

https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/c1e82485-cd4c-480d-9450-2c84c127e73f


https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/233995af-2e73-476f-996f-0a938dc11a3c

**Comment by DuriSK** [comment]
fixed
