### ISSUE TITLE
vDOT balance on Bifrost not correct

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/HydraDX-ui#864]
1. XCM 0.812 vDOT from Hydra to Bifrost 
https://bifrost.subscan.io/xcm_message/polkadot-86ea9779a808f0861017ed894c64e2d9b7cd7140

2. Balance on UI is showing 0.00812 vDOT on Bifrost, cant transfer them
<img width="586" alt="Screenshot 2023-12-29 at 13 24 50" src="https://github.com/galacticcouncil/HydraDX-ui/assets/97346452/cfe9a5a8-301d-4b32-a6fe-81b268d93c17">

**Comment by mrq1911** [comment]
fixed
