### ISSUE TITLE
DOT HydraDX > Polkadot transfer not working

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/HydraDX-ui#865]
User is attempting to CROSS-CHAIN DOT from HydraDX to Polkadot using our UI, has tried using multiple wallets and chrome & firefox browsers.

"Just FYI: I'm also getting errors about "max transferrable is 0" which I fixed by sending some DOT to the receiving end, now max transferrable is more than 0 but a lot less than expected? strange"

Consoles emitting the following errors:

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'key')
    at Ap.processTx (vendor-4f2f741f.js:12566:358)
    at Ap.swap (vendor-4f2f741f.js:12566:2091)`

`processTx https://app.hydradx.io/assets/vendor-26804027.js:12566
    swap https://app.hydradx.io/assets/vendor-26804027.js:12566
    xcmFormTab https://app.hydradx.io/assets/vendor-26804027.js:12625
    handleEvent https://app.hydradx.io/assets/vendor-26804027.js:6925
    onTransferClick https://app.hydradx.io/assets/vendor-26804027.js:12299
    handleEvent https://app.hydradx.io/assets/vendor-26804027.js:6925
vendor-26804027.js:12566:314
    swap https://app.hydradx.io/assets/vendor-26804027.js:12566
    InterpretGeneratorResume self-hosted:1469
    AsyncFunctionNext self-hosted:852
    (Async: async)
    xcmFormTab https://app.hydradx.io/assets/vendor-26804027.js:12625
    handleEvent https://app.hydradx.io/assets/vendor-26804027.js:6925
    onTransferClick https://app.hydradx.io/assets/vendor-26804027.js:12299
    handleEvent https://app.hydradx.io/assets/vendor-26804027.js:6925`

**Comment by mrq1911** [comment]
relate to #863
