### ISSUE TITLE
Include bond maturity on otc

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/HydraDX-ui#869]
We have bond maturity in wallet and on trade UI, but not currently OTC - therefore with second bonds coming, users will get confused.

![Screenshot_20231230_083126_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/61757d87-c9f6-4a0f-bf84-5690a2c12e04)
![Screenshot_20231230_083315_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/0fdf3843-2c8f-452e-b4e8-63dc6f915300)
![Screenshot_20231230_083325_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/97540577/3e0bb978-5df0-47b2-ab1b-fae6ab70576d)

**Comment by DuriSK** [comment]
Resolved
