### ISSUE TITLE
handle inability to pay fees transaction validation error

### ISSUE THREAD

**Issue by mrq1911** [galacticcouncil/HydraDX-ui#871]
usually happens when you try to transfer some asset from chain that you don't have fee payment asset on

<img width="1415" alt="Screenshot_2023-12-30_at_00 18 26" src="https://github.com/galacticcouncil/HydraDX-ui/assets/2580779/4b7aae77-3686-46a2-a719-4dddcbe37cc9">

this should be validated and handled

**Comment by DuriSK** [comment]
New XCM validations prevent user to sign transaction if he doesnt fulfil conditions.
I was not able to reproduce this on prod anymore
