### ISSUE TITLE
Not taking in account the HDXb<>HDX liquidity value on the wallet tab

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/HydraDX-ui#913]
Shoul add the value of the liquidity of the xyk pool, and only show the 0.5 of the dot

![Screenshot_20240107_082701_Nova](https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/e218c508-c15e-44a6-b3ec-74e829111d42)

**Comment by DuriSK** [comment]
fixed
