### ISSUE TITLE
OTC trades reborn

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/HydraDX-ui#933]
We would like to optimise experience for OTC page

- Redesign the page based on provided design (passwd: Ben will provide)
  https://www.figma.com/file/RzkshqBUAQO5GQzDo89RtH/OTC-Design-Bounty?type=design&node-id=1-6222&mode=design&t=hzPt9PvbHyURHSwC-4

- Add search field at the top ,supporting full text search for assets (should look in both assets, offered and accepted) - name and symbol should be considered, so search should for both for HDX and Hydra
- Add pricing (from router for given pair) in column current spot price for given pair (getBestSpotPrice from router) - if the price is not available in router, consider using coingecko api as reference price
- Add % difference comparing to spot price for given asset (to let people know if deal is worth or not) for super bad deals, tag them in red, anything above 10% difference should be tagged. For bonds, consider underlying asset as price level (you can find out underlying asset of bond using bonds.bonds() )

Example:
<img width="1280" alt="sub1" src="https://github.com/galacticcouncil/HydraDX-ui/assets/97346452/ef407c11-147d-4731-92df-300f6e236516">
<img width="494" alt="Screenshot 2024-01-11 at 21 29 19" src="https://github.com/galacticcouncil/HydraDX-ui/assets/97346452/035b083d-dec4-4934-a2d8-97e37f376b71">

- Add proper Bond name (including maturity) 
- Add icon for Bonds
- deals should be by default sorted by price difference (best on the top)

Disable option to create new order for same asset (so user should be not able to create HDX/HDX offer)

**Comment by mrq1911** [comment]
table should be sorted by the deals (price difference) and then size

**Comment by mrq1911** [comment]
bonus points for integrating OTC into the router - so you can fill OTC order on the trade page when is effective price is better than any available pools

router could consider individual otc orders as pools with limited liquidity and 0 slippage
